// Backward-compatible exports. New code should use packLogic directly.
export {
  PACK_NAMES_BY_TIER,
  SHOP_UPGRADES,
  TIERS,
  RARITIES,
  MUTATIONS,
  MUTATION_RANK,
  getHighestUnlockedTier,
  getProgressToNextTier,
  getEffectiveTierWeights,
  getNextTierOddsChangeLevel,
  getBaseTierWeightsForBoostLevel,
  getRarityWeightsForTier,
  getMutationWeights,
  pickFromWeightedMap,
  normalizeMutation,
  mutationRank,
  bestMutation,
  getUpgradeCap,
  getUpgradeCost,
  getUpgradeLevel,
  getUpgradePreview,
  getAutoOpensPerSecond,
  getValueMultiplier,
  computeCardReward,
  canBuyUpgrade,
  applyUpgrade,
} from './packLogic.mjs'
